plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = "${mod_version}+${minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}


repositories {
	maven { url 'https://server.bbkr.space/artifactory/libs-release' }
	maven { url 'https://www.cursemaven.com' }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishMods {
	file = jar.archiveFile
	changelog = file("changelog.md").text
	type = STABLE
	modLoaders.add("fabric")

	modrinth {
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		projectId = "H6g6MTOB"
		minecraftVersions.addAll("${minecraft_version}")
		requires {
			slug = "fabric-api"
		}
	}

	curseforge {
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		projectId = "406691"
		displayName = "(${project.minecraft_version}) AdaPaxels $project.version"
		minecraftVersions.addAll("${minecraft_version}")
		requires {
			slug = "fabric-api"
		}
	}
}