# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.149.1+26.1.2

# Mod Properties
mod_version=1.7.0
maven_group=com.brand
archives_base_name=adapaxels